# Generated by Django 5.1.1 on 2024-10-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kittens_app', '0002_alter_breed_name_alter_kitten_age_alter_kitten_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitten',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
